export default {
    input: 'bot.js',
    output: {
        file: 'dist/bundle.js',
        format: 'es'
    },
    external: [
        'discord.js',
        '@discordjs/rest',
        'discord-api-types',
        'mongoose',
        'dotenv',
        'chalk',
        'colors',
        'winston',
        'pino',
        'dayjs',
        'moment',
        'node-fetch',
        'axios',
        'ms',
        'uuid',
        '@discordjs/builders',
        'humanize-duration',
        'pretty-ms',
        'msleep',
        'ascii-table',
        'figlet',
        'gradient-string',
        'boxen',
        'cli-spinners',
        'ora',
        'enmap',
        'quick.db',
        'lodash',
        'fs-extra',
        'path',
        'crypto',
        'express',
        'socket.io',
        'helmet',
        'cors',
        'nodemon',
        'pm2',
        'jsdom',
        'validator',
        'tinycolor2',
        'puppeteer',
        'sharp',

        '@babel/core',
        'prettier',
        'eslint',
        'husky',
        'lint-staged',
        'jest',
        'supertest',
        'cross-fetch',
        'form-data',
        'mime-types',
        'klaw',
        'emoji-regex',
        'string-similarity',
        'opusscript',
        'ffmpeg-static',
        'ytdl-core',
        'sound-play',
        'play-dl',
        'fluent-ffmpeg'
    ]
};